### ISSUE TITLE
不应该把“选项”表格中的“选项”列的内容翻译为中文

### ISSUE THREAD

**Issue by newbe36524** [NuGet/docs.microsoft.com-nuget.zh-cn#10]
不应该把“选项”表格中的“选项”列的内容翻译为中文

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a3d9a003-8855-e57a-2f57-5a8e2ad831f2
* Version Independent ID: 68bacd53-48dc-bae3-4a51-207a7b9ce95f
* Content: [NuGet CLI 添加命令](https://docs.microsoft.com/zh-cn/nuget/tools/cli-ref-add)
* Content Source: [docs/tools/cli-ref-add.md](https://github.com/NuGet/docs.microsoft.com-nuget.zh-cn/blob/live/docs/tools/cli-ref-add.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by CeciAc** [comment]
你好，@newbe36524
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@newbe36524
感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：XXX。  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
