### ISSUE TITLE
所有命令的“选项”表格的“选项”列都不应该翻译为中文

### ISSUE THREAD

**Issue by newbe36524** [NuGet/docs.microsoft.com-nuget.zh-cn#11]
所有命令的“选项”表格的“选项”列都不应该翻译为中文。
所有的 nuget 命令页面，不仅仅包含下面链接所指向的内容。需要检查所有的表格。此处不一一列举。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5ffd3252-bc88-2f85-3d7a-3da879a49ae1
* Version Independent ID: 55ec713a-497f-4ac8-d1de-fb3d21d58702
* Content: [NuGet CLI 删除命令](https://docs.microsoft.com/zh-cn/nuget/tools/cli-ref-delete)
* Content Source: [docs/tools/cli-ref-delete.md](https://github.com/NuGet/docs.microsoft.com-nuget.zh-cn/blob/live/docs/tools/cli-ref-delete.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by CeciAc** [comment]
你好，@newbe36524
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@newbe36524

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/nuget/tools/cli-ref-delete

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
