### ISSUE TITLE
nuget 太慢了，真是个垃圾玩意

### ISSUE THREAD

**Issue by JavaScript-zt** [NuGet/docs.microsoft.com-nuget.zh-cn#7]
为什么nuget 下载这么慢，就不能弄个好一点的服务器吗，fuck u

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9ffc1aea-bed4-f33a-69e8-b0a339443d94
* Version Independent ID: ed0d51ba-df92-4e87-211b-2e0f6bc5da0c
* Content: [NuGet CLI update 命令](https://docs.microsoft.com/zh-cn/nuget/tools/cli-ref-update#feedback)
* Content Source: [docs/tools/cli-ref-update.md](https://github.com/NuGet/docs.microsoft.com-nuget.zh-cn/blob/live/docs/tools/cli-ref-update.md)
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by JavaScript-zt** [comment]
gg

**Comment by CeciAc** [comment]
你好，@JavaScript-zt

你的注释违反了我们行为准则，见 https://opensource.microsoft.com/codeofconduct/。  

因此，我们需要锁定并关闭此问题。 


深深的祝福， 
Microsoft DOCS International Team
