### ISSUE TITLE
不应该把选项列的内容翻译为中文

### ISSUE THREAD

**Issue by newbe36524** [NuGet/docs.microsoft.com-nuget.zh-cn#8]
“选项”列 本来就是用来指示配置项的，翻译为中文后将无法更好的查看。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 2e18eb26-7a73-5e48-abd0-3d53476c6f91
* Version Independent ID: 5469de95-4b00-2fbd-f3c0-1cde036f3c7f
* Content: [NuGet CLI pack 命令](https://docs.microsoft.com/zh-cn/nuget/tools/cli-ref-pack#feedback)
* Content Source: [docs/tools/cli-ref-pack.md](https://github.com/NuGet/docs.microsoft.com-nuget.zh-cn/blob/live/docs/tools/cli-ref-pack.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by CeciAc** [comment]
你好，@newbe36524
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@newbe36524
 
感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/nuget/tools/cli-ref-pack#feedback  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
